config/routes.rb
Depot::Application.routes.draw do

  get "store2/index"

  resources :books
  root to: 'sessions#create'
  resources :contacts

  resources :static_pages

   match 'store' => 'store#index'
   match 'about' => 'static_pages#about'
   match 'contact' => 'contacts#new', :as => 'contact'
   
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "admin/index"

  get "contacts/new"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "static_pages/home"

  get "empty" => 'carts#destroy'

  resources :store

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  resources :contacts

  resources :products 

  delete '/sessions/destroy(.:format)' => 'sessions#destroy', :as => 'logout'

  resources :products do
    get :who_bought, on: :member
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :line_items, dependent: :destroy

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :comment, :name, :phone
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :product
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def self.search(search, page)
    paginate :per_page => 5, :page => page,
      :conditions => ['name like ?', "%#{search}%"],
      :order => 'name'
  end

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :poem, :image_url, :price, :name, :birthday, :poem, :count
  validates :name, :image_url, :count, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  def self.search(search, page)
    paginate :per_page => 5, :page => page,
      :conditions => ['name like ?', "%#{search}%"],
      :order => 'name'
  end
  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  # attr_accessible :title, :body
  acts_as_gmappable

def gmaps4rails_address
#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
  "#{self.street}, #{self.city}, #{self.country}" 
end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store2_helper.rb
module Store2Helper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
	<title>Beanie Baby Hammock</title>
	
	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
	<?php require 'php'  ?>
	  <script type="text/javascript" src="XmlHttpRequest2.js"></script>  
	  
</head>
<body class="<%= controller.controller_name %>">
	
	<div id="banner">
		<div id=leftLogo>
			<%= image_tag("beanies.gif") %>
		</div>
		<%= @page_title || "Beanie Baby Hammock" %>

	</div>
	<div id="side">
		<ul>
				<li ><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Store", store_index_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><a href="http://hammock.silvernightfall.com/MouseOver.htm">Coming Soon</a></li>
				 <li><a href="http://hammock.silvernightfall.com/FeedRead3.php"><img src="rss.png" alt="rss feed" /></a></li>
			</ul>
			<% if @cart %>
			<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
			<%= render @cart %>
			<% end %>
			<% end %>

			<% if session[:user_id] %>
			<ul>
<li class="link"><%= button_to 'Logout', logout_path, method: :delete, id: "log" %></li>
				</ul>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>
		
		<div class="clearfooter"></div>
</div>
		<div class="footer">
			<ul>
				<li id="home"><%= link_to "Home", login_path, class: 'footer' %></li>
				<li id="about"><%= link_to "About", about_path, class: 'footer' %></li>
				<li id="store"><%= link_to "Store", store_index_path, class: 'footer'%></li>
				<li id="contact"><%= link_to "Contact", contact_path, class: 'footer' %></li>
				<li><a href="http://hammock.silvernightfall.com/MouseOver.htm">Coming Soon</a></li>
				 <li><a href="http://hammock.silvernightfall.com/FeedRead3.php">RSS</a></li>
			</ul>
		</div>
		<div id="copyright">

			<script type="text/javascript">document.write('&copy;&nbsp;' +(new Date()).getFullYear() + '&nbsp;&nbsp;Victoria Bagnell');</script><noscript>&copy;&nbsp;Victoria Bagnell</noscript>
		</div>
</body>
</html>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Beanie Baby Hammock.
You ordered the following items:
<%= render @order.line_items %>
We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Beanie Baby Hammock Order Shipped</h3>
<p>
	This is just to let you know that we've shipped your recent order:
</p>
<table>
	<tr><th colspan="2">Qty</th><th>Description</th></tr>
	<%= render @order.line_items %>
</table>